<a href="https://colab.research.google.com/github/ananyapoonsawat/BSC_DPDM23/blob/main/%E0%B8%97%E0%B8%94%E0%B8%AA%E0%B8%AD%E0%B8%9A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import pandas as pd

In [24]:
from google.colab import drive
drive.mount('/content/drive') # mount =  เชื่อมไดร์ฟ

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

#ประวัติการให้ทุนการศึกษาบุตรบุคลากร

##นำเข้าข้อมูล ประวัติการให้ทุนการศึกษาบุตรบุคลากร

In [21]:
data = pd.read_excel('/content/drive/MyDrive/ทุนบุตร.xlsx') #เรียกใช้ไฟล์ที่ต้องการ และ ตั้งหัวตาราง
data

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/ทุนบุตร.xlsx'

In [ ]:
aa = data['name'].str.startswith('ด.ช.','ด.ญ.')
#ลองเช็คข้อมูล
aa

0       False
1        True
2       False
3       False
4       False
        ...
4439    False
4440    False
4441    False
4442    False
4443    False
Name: name, Length: 4444, dtype: object

##เปลี่ยนข้อมูลคอลัมล์ columns ประวัติการให้ทุนการศึกษาบุตรบุคลากร

In [ ]:
data['name'] = data['name'].str.replace('เด็ฏชาย','ด.ช.')
data['name'] = data['name'].str.replace('เด็กชาย','ด.ช.')
data['name'] = data['name'].str.replace('เด็กหญฺง ','ด.ญ.')
data['name'] = data['name'].str.replace('เด้กหญิง','ด.ญ.')
data['name'] = data['name'].str.replace('เด็กหญิง','ด.ญ.')

data['name'] = data['name'].str.replace('ดช.','ด.ช.')
data['name'] = data['name'].str.replace('ดญ.','ด.ญ.')

data['name'] = data['name'].str.replace('ด.ช. ','ด.ช.')
data['name'] = data['name'].str.replace('ด.ญ. ','ด.ญ.')

data['name'] = data['name'].str.replace('ดช. ','ด.ช.')
data['name'] = data['name'].str.replace('ดญ. ','ด.ญ.')

data['name'] = data['name'].str.replace('นาย ','นาย')

data['name'] = data['name'].str.replace('นาง ','นาง')

data['name'] = data['name'].str.replace('นางสาว','น.ส.')
data['name'] = data['name'].str.replace('นางสาว ','น.ส.')
data['name'] = data['name'].str.replace('นางสาง','น.ส.')

data['name'] = data['name'].str.replace('น.ส. ','น.ส.')
data['name'] = data['name'].str.replace('นส.','น.ส.')

data['name']

0                   ด.ญ.จิตติมา  สุดใด
1              ด.ช.กันตพัฒน์  พิมพ์แมน
2                ด.ญ.พรรณปพร  แถลงธรรม
3              นายคงตระกูล  หรั่งยี่โถ
4            ด.ญ.กิตรดา  เวทีวุฒาจารย์
                     ...
4439            ด.ญ.เพลงณหทัย ภูศรีโสม
4440             ด.ญ.พราวณกมล ภูศรีโสม
4441    ด.ญ.เอวารินทร์ อินทร์ประสิทธิ์
4442                 ด.ญ.พรประภา ใจลึก
4443                   ด.ญ.พีรดา ใจลึก
Name: name, Length: 4444, dtype: object

In [ ]:
data

,sequence,id,identification,sday,idp,name,sch,term,lev,total,sal,ref,filebaby,note,usr,time
0,1,112564,5.401000e+12,2018-10-18,1409904001761,ด.ญ.จิตติมา สุดใด,โรงเรียนสาธิตมหาวิทยาลัย,เทอมต้น,>ป.1,16000.0,7000,ใบเสร็จรับเงิน,112564_20190523 _133948.pdf,NaN,มณีวรรณ มุสิกะสาร,2019-05-23 13:39:48
1,3,115409,3.409700e+12,2018-10-18,1409903664278,ด.ช.กันตพัฒน์ พิมพ์แมน,โรงเรียนฮั่วเคี้ยววิทยาลัย,เทอมต้น,ป.5,7540.0,7000,ใบเสร็จรับเงิน,115409_20190523 _111126.pdf,NaN,มณีวรรณ มุสิกะสาร,2019-05-23 11:11:26
2,5,115640,1.539900e+12,2018-10-18,1409904269224,ด.ญ.พรรณปพร แถลงธรรม,โรงเรียนอนุบาลขอนแก่น,เทอมต้น,อ.1,8800.0,7000,NaN,NaN,NaN,NaN,2018-10-18 13:28:28
3,7,109387,3.300101e+12,2018-10-18,1309903039251,นายคงตระกูล หรั่งยี่โถ,วิทยาลัยอาชีวศึกษาขอนแก่น,เทอมต้น,ปวช.,5350.0,7000,NaN,NaN,NaN,NaN,2018-10-18 13:28:28
4,9,113118,3.439900e+12,2018-10-18,1409904112732,ด.ญ.กิตรดา เวทีวุฒาจารย์,โรงเรียนสาธิตมหาวิทยาลัย,เทอมต้น,อ.2,15000.0,7000,NaN,NaN,NaN,NaN,2018-10-18 13:28:28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4439,8839,118720,NaN,2023-04-26,1479901161660,ด.ญ.เพลงณหทัย ภูศรีโสม,โรงเรียนอนุบาลโสธิญา,เทอมต้น,>ป.3,10843.0,7000,ใบเสร็จรับเงิน เล่มที่ 005 เลขที่ 4167,118720_20230810 _173348.pdf,NaN,ยุวรรณา เลิศศิริ,2023-08-10 17:33:48
4440,8841,118720,NaN,2023-04-26,1479901250484,ด.ญ.พราวณกมล ภูศรีโสม,โรงเรียนอนุบาลโสธิญา,เทอมต้น,>ป.1,8324.0,7000,ใบเสร็จรับเงิน เล่มที่ 004 เลขที่ 3914,118720_20230810 _173515.pdf,NaN,ยุวรรณา เลิศศิริ,2023-08-10 17:35:15
4441,8843,124281,NaN,2023-06-22,1409904769481,ด.ญ.เอวารินทร์ อินทร์ประสิทธิ์,โรงเรียนสาธิตมหาวิทยาลัยขอนแก่น,เทอมต้น,>อ.1,14000.0,7000,ใบเสร็จรับเงิน เล่มที่ 322 เลขที่ 321860,124281_20230816 _183253.pdf,NaN,ยุวรรณา เลิศศิริ,2023-08-16 18:32:54
4442,8845,132129,NaN,2024-01-10,1529902713720,ด.ญ.พรประภา ใจลึก,โรงเรียนอนุบาลสาธิตเทศบาลนครขอนแก่น (โนนหนองวัด),เทอมปลาย,>อ.3,0.0,7000,หนังสือรับรอง,132129_20240316 _110008.pdf,NaN,ยุวรรณา เลิศศิริ,2024-03-16 11:00:08
4443,8847,132129,NaN,2023-12-08,1409904827995,ด.ญ.พีรดา ใจลึก,โรงเรียนบ้านพร้อมบุญ,เทอมปลาย,>อ.1,14000.0,7000,ใบเสร็จรับเงิน เล่มที่ 282 เลขที่ 14092,132129_20240316 _110242.pdf,NaN,ยุวรรณา เลิศศิริ,2024-03-18 11:29:15

##Save ข้อมูล ประวัติการให้ทุนการศึกษาบุตรบุคลากร

In [31]:
pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (3.1.2)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl) (1.1.0)

In [ ]:
df = pd.DataFrame(data)

# บันทึก DataFrame เป็นไฟล์ Excel
df.to_excel('ประวัติการให้ทุนการศึกษาบุตรบุคลากร(python).xlsx', index=False)
#Downlaod ไฟล์

NameError: name 'data' is not defined

#ประวัติการรับทุนของบุคลากร

##นำเข้าข้อมูล ประวัติการรับทุนของบุคลากร

In [22]:
dv = pd.read_excel('/content/drive/MyDrive/ข้อมูล กองทรัพย์/ประวัติการรับทุนของบุคลากร.xlsx') #เรียกใช้ไฟล์ที่ต้องการ และ ตั้งหัวตาราง
dv

,seq,id,startday,stopday,name,rname,level,course,major,place,country,sal,note,usr,time
0,1,109776,2001-06-01,2007-05-30,โครงการพัฒนาอาจารย์สาขาขาดแคลน,อาจารย์,ปริญญาเอก,นานาชาติ,สาธารณสุขศาสตร์,จุฬาลงกรณ์มหาวิทยาลัย,ไทย,594860,NaN,วารุณี แก้ววันทา,2013-06-24 10:54:24
1,2,109375,2001-06-01,2002-05-29,โครงการพัฒนาอาจารย์สาขาขาดแคลน,อาจารย์,ปริญญาโท,นานาชาติ,เศรษฐศาสตร์สาธารณสุข,จุฬาลงกรณ์มหาวิทยาลัย,ไทย,216171,NaN,วารุณี แก้ววันทา,2004-11-29 11:50:43
2,3,102978,2001-06-01,2006-04-10,โครงการพัฒนาอาจารย์สาขาขาดแคลน,อาจารย์,ปริญญาเอก,นานาชาติ,ระบาดวิทยา,มหาวิทยาลัยมหิดล,ไทย,440775,NaN,วารุณี แก้ววันทา,2008-03-12 15:47:11
3,4,109775,2001-06-01,2003-08-19,โครงการพัฒนาอาจารย์สาขาขาดแคลน,อาจารย์,ปริญญาเอก,ปกติ,เภสัชวิทยา,มหาวิทยาลัยขอนแก่น,ไทย,108550,NaN,วารุณี แก้ววันทา,2008-03-12 15:48:53
4,5,109991,2001-06-01,2004-04-02,โครงการพัฒนาอาจารย์สาขาขาดแคลน,อาจารย์,ปริญญาโท,ปกติ,ทันตกรรมทั่วไป,มหาวิทยาลัยมหิดล,ไทย,208320,NaN,วารุณี แก้ววันทา,2005-01-18 15:19:28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
473,521,119707,2023-03-01,NaT,ทุนการศึกษาต่อระดับปริญญาเอก ณ ต่างประเทศ สำหร...,NaN,ปริญญาเอก,ปรัชญาดุษฎีบัณฑิต,Applied Linguistics (ภาษาศาสตร์ประยุกต์),Massey University,นิวซีแลนด์,800000,"วงเงิน 800,000 บาท/ปี ระยะเวลา 3 ปี ตั้งแต่วัน...",วารุณี ไพรพยอม,2023-03-03 10:58:02
474,523,118782,2023-07-03,NaT,ทุนการศึกษาต่อระดับปริญญาเอกในประเทศ สำหรับอาจ...,NaN,ปริญญาเอก,NaN,นิติศาสตร์,มหาวิทยาลัยธรรมศาสตร์,ไทย,60500,ระยะเวลารับทุน 3 ปี เริ่มตั้งแต่ภาคปลาย ปี 256...,วารุณี ไพรพยอม,2024-02-20 15:03:18
475,525,128187,2024-06-01,NaT,ทุนการศึกษาต่อระดับปริญญาเอกในประเทศ สำหรับอาจ...,NaN,ปริญญาเอก,NaN,Business,มหาวิทยาลัยขอนแก่น,ไทย,90000,ระยะเวลารับทุน 1 ปี เริ่มตั้งแต่ภาคต้น ปี 2567...,วารุณี ไพรพยอม,2024-02-20 15:12:33
476,527,128447,2024-03-04,2027-03-03,ทุนการศึกษาต่อระดับปริญญาเอก ณ ต่างประเทศ สำหร...,NaN,ปริญญาเอก,NaN,PhD Korean,Yonsei University,เกาหลี,800000,ระยะเวลารับทุน 3 ปี ตั้งแต่วันที่ 4 มี.ค. 67 ถ...,วารุณี ไพรพยอม,2024-02-20 15:43:21
477,529,125707,2023-09-30,2026-09-29,ทุนการศึกษาต่อระดับปริญญาเอก ณ ต่างประเทศ สำหร...,NaN,ปริญญาเอก,NaN,PhD Design,Queensland University of Technology,ออสเตรเลีย,800000,NaN,วารุณี ไพรพยอม,2024-02-20 15:42:20

##เปลี่ยนข้อมูลคอลัมล์ columns ประวัติการรับทุนของบุคลากร

In [25]:
dv['course'] = dv['course'].str.replace('ปริญญาเอกร่วมกับมหาวิยาลัยในต่างประเทศ','ปริญญาเอกร่วมกับมหาวิทยาลัยในต่างประเทศ')
dv['course'] = dv['course'].str.replace('ปริญญาเอกร่วมร่วมกับมหาวิทยาลัยในต่างประเทศ','ปริญญาเอกร่วมกับมหาวิทยาลัยในต่างประเทศ')

In [26]:
dv['major'] = dv['major'].str.replace('Nursitng','Nursing')
dv['major'] = dv['major'].str.replace('Romete Sensing & GIS','Remote Sensing & GIS')
dv['major'] = dv['major'].str.replace('Remote Sensing and GIS','Remote Sensing & GIS')
dv['major'] = dv['major'].str.replace('เทคโนโลยีการอาหาร','เทคโนโลยีทางอาหาร')
dv['major'] = dv['major'].str.replace('เทคโนโลยีอาหาร','เทคโนโลยีทางอาหาร')

In [27]:
dv['place'] = dv['place'].str.replace('Linclon University','Lincoln University')
dv['place'] = dv['place'].str.replace('มหาวิทยาลัยศรีนครินทร์วิโรฒ','มหาวิทยาลัยศรีนครินทรวิโรฒ')
dv['place'] = dv['place'].str.replace('มหาวิทยาลัยเกตษรศาสตร์','มหาวิทยาลัยเกษตรศาสตร์')
dv['place'] = dv['place'].str.replace('คณะแพทยศาสตร์ ม.ขอนแก่น','คณะแพทยศาสตร์ มหาวิทยาลัยขอนแก่น')
dv['place'] = dv['place'].str.replace('มหาวิทยาลัยขอนแกน','มหาวิทยาลัยขอนแก่น')
dv['place'] = dv['place'].str.replace('คณะพยาบาลศาสตร์ ม.ขอนแก่น','คณะพยาบาลศาสตร์ มหาวิทยาลัยขอนแก่น')
dv['place'] = dv['place'].str.replace('คณะแพทยศาสตร์ ม.มหิดล','คณะแพทยศาสตร์ มหาวิทยาลัยมหิดล')
dv['place'] = dv['place'].str.replace('มหาหาวิทยาลัยขอนแก่น','มหาวิทยาลัยขอนแก่น')
dv['place'] = dv['place'].str.replace('มหาวิทยาัยขอนแก่น','มหาวิทยาลัยขอนแก่น')
dv['place'] = dv['place'].str.replace('สถาบันบัณฑิตพัฒนาบริหารศาสตร์','สถาบันบัณฑิตพัฒนบริหารศาสตร์')
dv['place'] = dv['place'].str.replace('รพ.จุฬาลงกรณ์','โรงพยาบาลจุฬาลงกรณ์')
dv['place'] = dv['place'].str.replace('สถาบันเทคโนโลยีพระจอมเกล้าลาดกระบัง','สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง')

In [28]:
dv['country'] = dv['country'].str.replace('ไทบ','ไทย')
dv['country'] = dv['country'].str.replace('เยอรมัน','เยอรมนี')
dv['country'] = dv['country'].str.replace('สหหรัฐอเมริกา','สหรัฐอเมริกา')

##แสดงตาราง dv

In [29]:
dv

,seq,id,startday,stopday,name,rname,level,course,major,place,country,sal,note,usr,time
0,1,109776,2001-06-01,2007-05-30,โครงการพัฒนาอาจารย์สาขาขาดแคลน,อาจารย์,ปริญญาเอก,นานาชาติ,สาธารณสุขศาสตร์,จุฬาลงกรณ์มหาวิทยาลัย,ไทย,594860,NaN,วารุณี แก้ววันทา,2013-06-24 10:54:24
1,2,109375,2001-06-01,2002-05-29,โครงการพัฒนาอาจารย์สาขาขาดแคลน,อาจารย์,ปริญญาโท,นานาชาติ,เศรษฐศาสตร์สาธารณสุข,จุฬาลงกรณ์มหาวิทยาลัย,ไทย,216171,NaN,วารุณี แก้ววันทา,2004-11-29 11:50:43
2,3,102978,2001-06-01,2006-04-10,โครงการพัฒนาอาจารย์สาขาขาดแคลน,อาจารย์,ปริญญาเอก,นานาชาติ,ระบาดวิทยา,มหาวิทยาลัยมหิดล,ไทย,440775,NaN,วารุณี แก้ววันทา,2008-03-12 15:47:11
3,4,109775,2001-06-01,2003-08-19,โครงการพัฒนาอาจารย์สาขาขาดแคลน,อาจารย์,ปริญญาเอก,ปกติ,เภสัชวิทยา,มหาวิทยาลัยขอนแก่น,ไทย,108550,NaN,วารุณี แก้ววันทา,2008-03-12 15:48:53
4,5,109991,2001-06-01,2004-04-02,โครงการพัฒนาอาจารย์สาขาขาดแคลน,อาจารย์,ปริญญาโท,ปกติ,ทันตกรรมทั่วไป,มหาวิทยาลัยมหิดล,ไทย,208320,NaN,วารุณี แก้ววันทา,2005-01-18 15:19:28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
473,521,119707,2023-03-01,NaT,ทุนการศึกษาต่อระดับปริญญาเอก ณ ต่างประเทศ สำหร...,NaN,ปริญญาเอก,ปรัชญาดุษฎีบัณฑิต,Applied Linguistics (ภาษาศาสตร์ประยุกต์),Massey University,นิวซีแลนด์,800000,"วงเงิน 800,000 บาท/ปี ระยะเวลา 3 ปี ตั้งแต่วัน...",วารุณี ไพรพยอม,2023-03-03 10:58:02
474,523,118782,2023-07-03,NaT,ทุนการศึกษาต่อระดับปริญญาเอกในประเทศ สำหรับอาจ...,NaN,ปริญญาเอก,NaN,นิติศาสตร์,มหาวิทยาลัยธรรมศาสตร์,ไทย,60500,ระยะเวลารับทุน 3 ปี เริ่มตั้งแต่ภาคปลาย ปี 256...,วารุณี ไพรพยอม,2024-02-20 15:03:18
475,525,128187,2024-06-01,NaT,ทุนการศึกษาต่อระดับปริญญาเอกในประเทศ สำหรับอาจ...,NaN,ปริญญาเอก,NaN,Business,มหาวิทยาลัยขอนแก่น,ไทย,90000,ระยะเวลารับทุน 1 ปี เริ่มตั้งแต่ภาคต้น ปี 2567...,วารุณี ไพรพยอม,2024-02-20 15:12:33
476,527,128447,2024-03-04,2027-03-03,ทุนการศึกษาต่อระดับปริญญาเอก ณ ต่างประเทศ สำหร...,NaN,ปริญญาเอก,NaN,PhD Korean,Yonsei University,เกาหลี,800000,ระยะเวลารับทุน 3 ปี ตั้งแต่วันที่ 4 มี.ค. 67 ถ...,วารุณี ไพรพยอม,2024-02-20 15:43:21
477,529,125707,2023-09-30,2026-09-29,ทุนการศึกษาต่อระดับปริญญาเอก ณ ต่างประเทศ สำหร...,NaN,ปริญญาเอก,NaN,PhD Design,Queensland University of Technology,ออสเตรเลีย,800000,NaN,วารุณี ไพรพยอม,2024-02-20 15:42:20

##Save ข้อมูล ประวัติการรับทุนของบุคลากร

In [33]:
#install pack pip install openpyxl
dv1 = pd.DataFrame(dv)
# บันทึก DataFrame เป็นไฟล์ Excel
dv1.to_excel('ประวัติการรับทุนของบุคลากร(python).xlsx', index=False)
#Downlaod ไฟล์